/* Generated by Together */

#ifndef CPLANERELATION_H
#define CPLANERELATION_H

enum EPlanesAttitude
{
	EPA_ATTACK_DIRECT,
	
	EPA_ATTACK_TAIL,
	EPA_GAIN_SPEED,
	EPA_GAIN_SPEED_FAST,
	EPA_GAIN_HEIGHT,
	EPA_GAIN_HEIGHT_FAST,
	EPA_RETREAT,
	
};

/** 1) определяет тип взаимодействия одного самолета относительно другого (см таблицу "поведение самолетов.xls". */
class CPlaneRelation 
{
public:

    /**
     * @url C:\home\a7\PlanePathTest\CManuverContainer.h 
     */
    int GetAttitude(const interface IPlane * pPlane, const interface IPlane *pEnemy);
};
#endif //CPLANERELATION_H